"""Baseline

Revision ID: 441116393d66
Revises: 
Create Date: 2026-05-10 19:33:54.365993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441116393d66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_abonos_venta'), table_name='abonos')
    op.drop_index(op.f('idx_productos_nombre'), table_name='productos')
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_ventas_fecha'), table_name='ventas')
    op.drop_index(op.f('idx_ventas_producto'), table_name='ventas')
    op.drop_index(op.f('idx_ventas_vendedor'), table_name='ventas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_ventas_vendedor'), 'ventas', ['vendedor_email'], unique=False)
    op.create_index(op.f('idx_ventas_producto'), 'ventas', ['producto_nombre'], unique=False)
    op.create_index(op.f('idx_ventas_fecha'), 'ventas', ['fecha_venta'], unique=False)
    op.alter_column('usuarios', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.create_index(op.f('idx_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('idx_abonos_venta'), 'abonos', ['venta_id'], unique=False)
    # ### end Alembic commands ###
